### ISSUE TITLE
Require PHP 7.1?

### ISSUE THREAD

**Issue by slaFFik** [drewm/drip#11]
Why are you requiring 7.1? I see that you added a return typehint - and that's all.

This is a breaking change, so it will be a 1.0 release, I suppose?

I won't be able to use it in my project than, and will need to stay with 0.8 :(

**Comment by drewm** [comment]
PHP 7.1 is the lowest supported version of PHP now, isn't it?

We're still on version `0.x.x` so all changes are fair game:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by slaFFik** [comment]
Yeah, you are correct for both claims. It's just you are not using actual things from newer PHP, thus I was wondering by bump it at all.

I'm using this lib in a WordPress plugin, so I can't afford to jump from 5.4 to 7.1.
I think I will backport most of the changes (except 7.1 and return type hinting) in my fork and use it instead.

**Comment by drewm** [comment]
Obviously it's not really in my interests to be supporting WordPress use, but I guess we could hold off a bit longer.
