### ISSUE TITLE
Posting Batches Not Working

### ISSUE THREAD

**Issue by jrhull** [drewm/drip#13]
Single updates work great. For some reason, getting this error when posting to `[/subscribers/batches](https://developer.drip.com/#batch-api)':

`Subscribers must contain between 1 and 1000 items`

Data before being sent is:

Dataset {#2564 ▼
  #label: "subscribers"
  #data: array:120 [▼

Any idea what is wrong here?

**Comment by drewm** [comment]
Are you using `DrewM\Drip\Batch`? If you list your code that might help.

**Comment by jrhull** [comment]
Oh, shoot - I didn't know that existed. I ended up hacking together something on my own using regular `Drip`:

` $Drip->post('subscribers/batches', ['batches' => [['subscribers' => $subscribers]]]);`

Maybe a note in the docs? (or I could just look harder next time)

**Comment by drewm** [comment]
Yes, I wouldn't have known it was there had you not asked and sent me looking. Apparently I added it 4 years ago 🤷‍♂ 

If you get it working and want to make a PR with an example, that'd be great. I don't actually use Drip at the moment, so I've not got an account to try it with.
