### ISSUE TITLE
Timeout 10 seconds

### ISSUE THREAD

**Issue by jaysmit9** [drewm/drip#2]
Thank you so much for this library!  Very handy with a recent job.  

Please consider changing the timeout value to 30 seconds.  

I had some batch calls that were pressing the limit of the Drip api.  (500 contacts, 100 custom fields per contact, a few tags per contact).  I was getting a timeout every 40-60 calls.  I moved the timeout to 30 seconds and this was resolved.

**Comment by drewm** [comment]
Hi @jaysmit9 - you can pass a timeout into any of the methods. I think it's the 3rd argument for each.

**Comment by slaFFik** [comment]
@drewm I believe this can be closed as you were correct with the timeout.
