### ISSUE TITLE
Purchases event

### ISSUE THREAD

**Issue by gertjanspriensma** [drewm/drip#3]
It seems like posting a purchasing event is not working. Probably due to the different way of posting, https://api.getdrip.com/v2/YOUR_ACCOUNT_ID/subscribers/ID_OR_EMAIL/purchases
 vs  https://api.getdrip.com/v2/YOUR_ACCOUNT_ID/subscribers

Any plans to add this?

**Comment by drewm** [comment]
Would you not do something like

```
$Response = $Drip->post('subscribers/davy@example.com/purchases', $data);
```

Or am I missing something?

**Comment by drewm** [comment]
I'll mark this as closed for now. Reopen it if that doesn't work.
