### ISSUE TITLE
Why properties are private?

### ISSUE THREAD

**Issue by slaFFik** [drewm/drip#4]
Private properties don't allow to reuse them in own class, that extends `Drip` from this library. Example, `$this->api_endpoint` usage in own method.

Please make them `protected`.

**Comment by drewm** [comment]
Sure, looking forward to the PR.

**Comment by slaFFik** [comment]
Will do shortly.

**Comment by slaFFik** [comment]
@drewm PR created.
Will it be possible to merge and release it as a new version shortly or should I switch in own project to using own fork for now?

**Comment by drewm** [comment]
I'll take a look!
