### ISSUE TITLE
makeRequest() is account specific

### ISSUE THREAD

**Issue by slaFFik** [drewm/drip#5]
Method `makeRequest()` is account specific, as it assumes that all API requests are made against a certain account.

Although, Drip API allows to make top-level requests, like `/accounts`: http://developer.drip.com/#accounts

With that, your library and its `get()` etc methods are useless in certain scenarios, and developers need to extend the class to create own `makeRawRequest()` method (or similar, to send requests without `accountID` in request URL). 
~But while extending we face with a problem in #4.~

**Comment by slaFFik** [comment]
@drewm, will you accept PR with this new method?

`makeRawRequest()` should be public, as it doesn't have a corresponding `get()`.

<details>
<summary>makeRawRequest()</summary>

```php
	/**
	 * Make a request to Drip API without anchoring to accountID.
	 * Example: /accounts. See http://developer.drip.com/#accounts for more details.
	 *
	 * @param string $http_verb Possible values: get, post, delete.
	 * @param string $api_method Example: accounts.
	 * @param array  $args Array of arguments to pass further to API.
	 * @param int    $timeout Allowed time frame for a request.
	 *
	 * @return Response
	 * @throws \Exception
	 */
	public function makeRawRequest( $http_verb = 'post', $api_method, $args = array(), $timeout = 10 ) {
		$url = $this->api_endpoint . '/' . $api_method;

		if ( function_exists( 'curl_init' ) && function_exists( 'curl_setopt' ) ) {

			$ch = curl_init();
			curl_setopt( $ch, CURLOPT_RETURNTRANSFER, 1 );
			curl_setopt( $ch, CURLOPT_HTTPHEADER, [
				'Accept: application/vnd.api+json',
				'Content-Type: application/vnd.api+json',
			] );
			curl_setopt( $ch, CURLOPT_USERAGENT, 'DrewM/Drip (github.com/drewm/drip)' );
			curl_setopt( $ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC );
			curl_setopt( $ch, CURLOPT_USERPWD, $this->token . ': ' );
			curl_setopt( $ch, CURLOPT_SSL_VERIFYPEER, $this->verify_ssl );
			curl_setopt( $ch, CURLOPT_TIMEOUT, $timeout );
			curl_setopt( $ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_0 );
			curl_setopt( $ch, CURLOPT_URL, $url );

			switch ( $http_verb ) {
				case 'post':
					curl_setopt( $ch, CURLOPT_POST, 1 );
					curl_setopt( $ch, CURLOPT_POSTFIELDS, json_encode( $args ) );
					break;

				case 'get':
					$query = http_build_query( $args );
					curl_setopt( $ch, CURLOPT_URL, $url . '?' . $query );
					break;

				case 'delete':
					curl_setopt( $ch, CURLOPT_CUSTOMREQUEST, 'DELETE' );
					break;
			}

			$result = curl_exec( $ch );

			if ( ! curl_errno( $ch ) ) {
				$info = curl_getinfo( $ch );
				curl_close( $ch );

				return new Response( $info, $result );
			}

			$errno = curl_errno( $ch );
			$error = curl_error( $ch );

			curl_close( $ch );

			throw new \Exception( $error, $errno );
		} else {
			throw new \Exception( "cURL support is required, but can't be found.", 1 );
		}
	}
```

</details>

It's more like a hack, but otherwise, the lib rewrite is required to chain `$url` properly depending on the context.

**Comment by slaFFik** [comment]
Hi, @drewm,

Is it possible to get your thoughts about this?

**Comment by slaFFik** [comment]
@drewm This issue was closed by mistake.
Can you reopen it please?

**Comment by drewm** [comment]
Sorry, not sure how that happened.

**Comment by slaFFik** [comment]
While you are here, would be nice to get your ideas about this issue and provided solution :)

**Comment by drewm** [comment]
Would you not construct an instance for each account?

```php
$DripAccount1 = new Drip('abc123', '1234567');
$DripAccount2 = new Drip('def456', '987654');
```

**Comment by drewm** [comment]
Sorry, I misunderstood - we need a way to make requests with no account ID, correct?

**Comment by slaFFik** [comment]
Yes. Drip API supports requests to get the list of accounts, for example. And for such requests, there is no account ID.
Currently, your lib just doesn't support that.

**Comment by drewm** [comment]
Would a nice way to do it be to maintain a list of those top-level methods in the class and check against them when constructing the URL?

We could also have a method to add to the list dynamically, which would provide a way to work around if the list were to lag behind API changes for any reason.

**Comment by slaFFik** [comment]
https://developer.drip.com/#list-all-accounts is the only example as far as I can see from the docs right now.

But I still don't think that having a whitelist for top-level requests is a good idea.

As this is the only API method, it might be a good idea to just have `public static getAccounts()` method to do just that.

**Comment by drewm** [comment]
I've pushed a new `getGlobal()` method to master.

```php
$Drip->getGlobal('accounts');
$Drip->getGlobal('accounts/1234');
```

It makes GET requests without the account ID.

Do you think that'll work?

**Comment by slaFFik** [comment]
Better than nothing.
`$url` can be property, so there will be no need to pass it to `makeRequest()`.

With the current approach I still need to init Drip with dummy data like `new Drip('api123', '')` (and then re-init with a correct account ID after `getGlobal()` usage) OR extend and redefine `__construct()` to not require `$accountId`.

**Comment by drewm** [comment]
> With the current approach I still need to init Drip with dummy data like new Drip('api123', '') (and then re-init with a correct account ID after getGlobal() usage)

Why?

**Comment by slaFFik** [comment]
How am I supposed to use new `getGlobal()`?
```php
$drip = new Drip($api, false);
$resposne = $drip->getGlobal();
// get `$accountId` from $reponse.
$drip2 = new Drip($api, $accountId);
$drip2->get();
```
That's what I need to do right now, because of the required arguments in `__construct($token, $accountID)`.
And AFTER I processed `$response` I need to re-init Drip again (create a new object) to make usual `get()` requests, because I get an actual account ID only after processing `$response`.

**Comment by drewm** [comment]
Ok, I see what you're saying. That seems very specific to your code, but it would be nice to provide a better way to support it.

How about this?

```php
$drip = new Drip($api);
$response = $drip->getGlobal('accounts');
// get `$accountId` from $response.
$drip->setAccountId($accountId);
$drip->get(...);
```

**Comment by slaFFik** [comment]
That's what I was hoping to suggest.
That approach works for me.

**Comment by drewm** [comment]
Ok, that should work now.
